=== BrunoPrzCu/SEW/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ATTLIST rutas 
    xmlns CDATA #FIXED "http://www.uniovi.es"
    xmlns:xsi CDATA #IMPLIED
    xsi:schemaLocation CDATA #IMPLIED>

<!ELEMENT ruta (nombre, tipo, medioTransporte, fechaInicio?, horaInicio?, duracion, agencia, descripcion, personasAdecuadas, lugarInicio, direccionInicio, coordenadasInicio, referencias, recomendacion, hitos, planimetria, altimetria)>
<!ATTLIST ruta id ID #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT medioTransporte (#PCDATA)>
<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personasAdecuadas (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>

<!ELEMENT coordenadasInicio (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT recomendacion (#PCDATA)>

<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre, descripcion, coordenadas, distancia, fotografias, videos?)>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>

<!ELEMENT fotografias (fotografia+)>
<!ELEMENT fotografia (#PCDATA)>

<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT planimetria (#PCDATA)>
<!ELEMENT altimetria (#PCDATA)>

=== BrunoPrzCu/SEW/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas xmlns="http://www.uniovi.es"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
    
    <ruta id="ruta1">
        <nombre>Ruta del Valle y los Pozos Mineros</nombre>
        <tipo>Paisajística e histórica</tipo>
        <medioTransporte>A pie</medioTransporte>
        <fechaInicio>2025-06-15</fechaInicio>
        <horaInicio>09:30:00</horaInicio>
        <duracion>4 horas</duracion>
        <agencia>Turismo SMRA</agencia>
        <descripcion>Un recorrido por el Valle de Santa Bárbara que permite descubrir el patrimonio industrial minero de San Martín del Rey Aurelio, adentrándose en la historia de la cuenca minera asturiana mientras se disfruta de hermosos paisajes.</descripcion>
        <personasAdecuadas>Personas en buena forma física</personasAdecuadas>
        <lugarInicio>Plaza del Ayuntamiento de San Martín</lugarInicio>
        <direccionInicio>Calle La Cuesta, 28</direccionInicio>
        <coordenadasInicio>
            <longitud>-5.606585</longitud>
            <latitud>43.275458</latitud>
            <altitud>275</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia>https://www.turismoasturias.es/descubre/donde-ir/otros-recursos/pozos-mineros</referencia>
            <referencia>http://www.museominero.es/</referencia>
            <referencia>https://www.smra.eu/turismo/que-visitar/</referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        
        <hitos>
            <hito>
                <nombre>Pozo San Vicente</nombre>
                <descripcion>Uno de los pozos mineros más emblemáticos de la cuenca del Nalón, con su característica torre de extracción que domina el paisaje. Rehabilitado para visitas turísticas.</descripcion>
                <coordenadas>
                    <longitud>-5.605033</longitud>
                    <latitud>43.279872</latitud>
                    <altitud>290</altitud>
                </coordenadas>
                <distancia unidades="km">1.2</distancia>
                <fotografias>
                    <fotografia>multimedia/pozo_san_vicente1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Mirador del Valle</nombre>
                <descripcion>Un punto privilegiado desde donde se puede contemplar todo el valle del Nalón, con sus poblaciones y el contraste entre la naturaleza y el paisaje industrial.</descripcion>
                <coordenadas>
                    <longitud>-5.598124</longitud>
                    <latitud>43.283561</latitud>
                    <altitud>450</altitud>
                </coordenadas>
                <distancia unidades="km">2.5</distancia>
                <fotografias>
                    <fotografia>multimedia/mirador_valle1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Antiguo Lavadero de Carbón</nombre>
                <descripcion>Estructura industrial rehabilitada donde se realizaba el lavado del carbón extraído de las minas. Hoy forma parte del patrimonio histórico industrial de la zona.</descripcion>
                <coordenadas>
                    <longitud>-5.592759</longitud>
                    <latitud>43.281248</latitud>
                    <altitud>310</altitud>
                </coordenadas>
                <distancia unidades="km">1.8</distancia>
                <fotografias>
                    <fotografia>multimedia/lavadero1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Bocamina Restaurada</nombre>
                <descripcion>Entrada a una antigua galería minera que ha sido acondicionada para poder visitar y experimentar cómo era el trabajo en el interior de las minas de carbón.</descripcion>
                <coordenadas>
                    <longitud>-5.588124</longitud>
                    <latitud>43.279015</latitud>
                    <altitud>295</altitud>
                </coordenadas>
                <distancia unidades="km">1.3</distancia>
                <fotografias>
                    <fotografia>multimedia/bocamina1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Museo de la Minería</nombre>
                <descripcion>Centro cultural que recoge la historia y tradiciones mineras de San Martín del Rey Aurelio, con exposiciones de herramientas, fotografías y recreaciones de la vida minera.</descripcion>
                <coordenadas>
                    <longitud>-5.606125</longitud>
                    <latitud>43.277230</latitud>
                    <altitud>280</altitud>
                </coordenadas>
                <distancia unidades="km">2.2</distancia>
                <fotografias>
                    <fotografia>multimedia/museo_mineria.jpg</fotografia>
                    <fotografia>multimedia/museo_mineria2.jpg</fotografia>
                    <fotografia>multimedia/museo_mineria3.jpg</fotografia>
                </fotografias>
                <videos>
                    <video>multimedia/recorrido_museo.mp4</video>
                </videos>
            </hito>
        </hitos>
        <planimetria>ruta1.kml</planimetria>
        <altimetria>ruta1.svg</altimetria>
    </ruta>
    
    <ruta id="ruta2">
        <nombre>Senda Verde del Nalón</nombre>
        <tipo>Naturaleza</tipo>
        <medioTransporte>Bicicleta</medioTransporte>
        <fechaInicio>2025-07-20</fechaInicio>
        <horaInicio>10:00:00</horaInicio>
        <duracion>3 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>Recorrido por la antigua vía del tren minero, convertida ahora en una senda verde que permite disfrutar de la naturaleza a lo largo del río Nalón, observando la flora y fauna local.</descripcion>
        <personasAdecuadas>Se puede ir con niños</personasAdecuadas>
        <lugarInicio>Estación de tren abandonada</lugarInicio>
        <direccionInicio>Carretera AS-117, km 5</direccionInicio>
        <coordenadasInicio>
            <longitud>-5.612387</longitud>
            <latitud>43.269845</latitud>
            <altitud>260</altitud>
        </coordenadasInicio>
        <referencias>
            <referencia>https://www.viasverdes.com/asturias/</referencia>
            <referencia>https://www.alltrails.com/es/spain/asturias/san-martin-del-rey-aurelio</referencia>
            <referencia>https://www.wikiloc.com/mountain-biking-trails/senda-verde-del-nalon</referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        
        <hitos>
            <hito>
                <nombre>Puente de hierro</nombre>
                <descripcion>Antiguo puente ferroviario que cruza sobre el río Nalón, testimonio de la época industrial de la zona, ahora rehabilitado para el paso de senderistas y ciclistas.</descripcion>
                <coordenadas>
                    <longitud>-5.608214</longitud>
                    <latitud>43.266912</latitud>
                    <altitud>255</altitud>
                </coordenadas>
                <distancia unidades="km">1.5</distancia>
                <fotografias>
                    <fotografia>multimedia/puente_hierro1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Meandro del Nalón</nombre>
                <descripcion>Curva pronunciada del río Nalón que forma un paisaje de gran belleza, rodeado de bosque de ribera y con diversas especies de aves acuáticas.</descripcion>
                <coordenadas>
                    <longitud>-5.601268</longitud>
                    <latitud>43.264789</latitud>
                    <altitud>250</altitud>
                </coordenadas>
                <distancia unidades="km">2.3</distancia>
                <fotografias>
                    <fotografia>multimedia/meandro1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Área recreativa Los Alisos</nombre>
                <descripcion>Zona de descanso junto al río, con mesas, bancos y fuente, ideal para hacer una pausa en la ruta y disfrutar del entorno natural.</descripcion>
                <coordenadas>
                    <longitud>-5.593155</longitud>
                    <latitud>43.262546</latitud>
                    <altitud>248</altitud>
                </coordenadas>
                <distancia unidades="km">2.7</distancia>
                <fotografias>
                    <fotografia>multimedia/area_recreativa1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Bosque de castaños centenarios</nombre>
                <descripcion>Pequeño bosque con ejemplares de castaños de gran antigüedad, algunos con más de 300 años, que muestran la riqueza natural de la región.</descripcion>
                <coordenadas>
                    <longitud>-5.587042</longitud>
                    <latitud>43.265123</latitud>
                    <altitud>275</altitud>
                </coordenadas>
                <distancia unidades="km">1.9</distancia>
                <fotografias>
                    <fotografia>multimedia/castanos1.jpg</fotografia>
                </fotografias>
            </hito>
            
            <hito>
                <nombre>Mirador del Río</nombre>
                <descripcion>Punto elevado desde el que se puede observar gran parte del recorrido del río Nalón y los valles que lo rodean, con vistas panorámicas excepcionales.</descripcion>
                <coordenadas>
                    <longitud>-5.582561</longitud>
                    <latitud>43.268792</latitud>
